### ISSUE TITLE
Deploy fails with Error monitoring subprocess with id 58265

### ISSUE THREAD

**Issue by gouthamhanur** [SAP/hana-shine-xsa#25]
Hi All,

I am trying to run XSA Shine SPS2 express edition , When i deploy the application after the build in WEBIDE , I'm getting an error . below is the error from xs client , i have followed it with logs from log files.
Can i know what is the best way to get more detailed logs when i deploy the app , 
i tried with set-loggin.. on deploy-service , but nothing changed in log files generated from deploy .

# **client log**

 Checking application "shine-core-db"...
 Application "shine-core-db" exists
 Updating application "shine-core-db"...
 Service "GOUTHAM_shine-container" will not be rebound to application "shine-core-db" because the binding parameters are not modified
 Service "GOUTHAM_shine-user-container" will not be rebound to application "shine-core-db" because the binding parameters are not modified
 Application "shine-core-db" is not modified and will not be updated
 Uploading application "shine-core-db"...
 Matched files count: 0
 Matched resources processed, total size is 0
 Upload status: finished
 Scaling application "shine-core-db"...
 Executing task "deploy" on application "shine-core-db"...
 Task execution status: pending
 Task execution status: failed
 Error executing task "deploy" on application "shine-core-db"
ERR    Error executing task "deploy" on application "shine-core-db".

# **Exception from log file.**
17 11 02 18:49:48.283#Z#DEBUG#com.sap.cloud.lm.sl.xs2.57650.MAIN_LOG#
######com.sap.cloud.lm.sl.slp.steps.SLProcessStepHelper########pool-6-thread-3###
Step "Execute Task" finished#

#2.0#2017 11 02 18:49:58.454#Z#DEBUG#com.sap.cloud.lm.sl.xs2.57650.MAIN_LOG#
######com.sap.cloud.lm.sl.cf.process.steps.StepsUtil########pool-6-thread-2###
[AbstractXS2SubProcessMonitorStep] Starting monitoring subprocess with id 58265#

#2.0#2017 11 02 18:49:58.458#Z#ERROR#com.sap.cloud.lm.sl.xs2.57650.MAIN_LOG#
######com.sap.cloud.lm.sl.cf.process.steps.StepsUtil########pool-6-thread-2###
[AbstractXS2ProcessStepWithBridge] **Error monitoring subprocess with id 58265#**

#2.0#2017 11 02 18:49:58.458#Z#ERROR#com.sap.cloud.lm.sl.xs2.57650.MAIN_LOG#
######com.sap.cloud.lm.sl.slp.steps.SLProcessStepHelper########pool-6-thread-2###
Exception caught#

com.sap.cloud.lm.sl.cf.process.exception.MonitoringException: Error monitoring subprocess with id 58265
	at com.sap.cloud.lm.sl.cf.process.steps.AbstractXS2SubProcessMonitorStep.pollStatusInternal(AbstractXS2SubProcessMonitorStep.java:28)
	at com.sap.cloud.lm.sl.cf.process.steps.AbstractXS2ProcessStepWithBridge.pollStatus(AbstractXS2ProcessStepWithBridge.java:29)
	at com.sap.activiti.common.impl.AbstractActivitiStepWithBridge.executeStep(AbstractActivitiStepWithBridge.java:59)
	at com.sap.activiti.common.impl.AbstractActivitiStep.execute(AbstractActivitiStep.java:56)
	at com.sap.cloud.lm.sl.slp.steps.AbstractSLProcessStepWithBridge.execute(AbstractSLProcessStepWithBridge.java:38)
	at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:96)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerStart.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerStart.java:52)
	at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:56)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:49)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionCreateScope.execute(AtomicOperationTransitionCreateScope.java:49)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.jobexecutor.AsyncContinuationJobHandler.execute(AsyncContinuationJobHandler.java:35)
	at org.activiti.engine.impl.persistence.entity.JobEntity.execute(JobEntity.java:85)
	at org.activiti.engine.impl.persistence.entity.MessageEntity.execute(MessageEntity.java:34)
	at org.activiti.engine.impl.cmd.ExecuteJobsCmd.execute(ExecuteJobsCmd.java:88)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti.engine.impl.jobexecutor.ExecuteJobsRunnable.handleMultipleJobs(ExecuteJobsRunnable.java:94)
	at org.activiti.engine.impl.jobexecutor.ExecuteJobsRunnable.run(ExecuteJobsRunnable.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:805)
#2.0#2017 11 02 18:49:58.458#Z#DEBUG#com.sap.cloud.lm.sl.xs2.57650.MAIN_LOG#
######com.sap.cloud.lm.sl.slp.steps.SLProcessStepHelper########pool-6-thread-2###
Step "MonitorSubProcess" finished#

**Comment by kiruthikan** [comment]
Hi Goutham,

Can you execute the following command and post the output here?

**xs logs shine-core-db --recent**

This would help us know the root cause for this failure.

Thanks and Regards,
Kiruthika

**Comment by kiruthikan** [comment]
Closing this as its has been inactive for a while.Please reopen if the issue persists.
