### ISSUE TITLE
[shine-cf] Controller operation failed: 400 Could not create service "shine-container"

### ISSUE THREAD

**Issue by jeejo-j** [SAP/hana-shine-xsa#28]
Hi Experts,

i am getting below error while deploying the shine application into cloud-foundry trial account in sap cloud platform, 

Api endpoint : https://api.cf.eu10.hana.ondemand.com

Stack trace : 

com.sap.cloud.lm.sl.common.SLException: Controller operation failed: 400 Could not create service "shine-container"
	at com.sap.cloud.lm.sl.cf.process.steps.StepsUtil.createException(StepsUtil.java:870)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.pollStatusInternal(CreateOrUpdateServicesStep.java:102)
	at com.sap.cloud.lm.sl.cf.process.steps.AbstractXS2ProcessStepWithBridge.pollStatus(AbstractXS2ProcessStepWithBridge.java:41)
	at com.sap.activiti.common.impl.AbstractActivitiStepWithBridge.executeStep(AbstractActivitiStepWithBridge.java:59)
	at com.sap.activiti.common.impl.AbstractActivitiStep.execute(AbstractActivitiStep.java:56)
	at com.sap.cloud.lm.sl.slp.steps.AbstractSLProcessStepWithBridge.execute(AbstractSLProcessStepWithBridge.java:38)
	at org.activiti.engine.impl.delegate.JavaDelegateInvocation.invoke(JavaDelegateInvocation.java:34)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)
	at org.activiti.engine.impl.delegate.DefaultDelegateInterceptor.handleInvocation(DefaultDelegateInterceptor.java:25)
	at org.activiti.engine.impl.bpmn.behavior.ServiceTaskDelegateExpressionActivityBehavior.execute(ServiceTaskDelegateExpressionActivityBehavior.java:96)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationActivityExecute.execute(AtomicOperationActivityExecute.java:60)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionNotifyListenerStart.eventNotificationsCompleted(AtomicOperationTransitionNotifyListenerStart.java:52)
	at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:56)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AbstractEventAtomicOperation.execute(AbstractEventAtomicOperation.java:49)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperationSync(ExecutionEntity.java:648)
	at org.activiti.engine.impl.persistence.entity.ExecutionEntity.performOperation(ExecutionEntity.java:643)
	at org.activiti.engine.impl.pvm.runtime.AtomicOperationTransitionCreateScope.execute(AtomicOperationTransitionCreateScope.java:49)
	at org.activiti.engine.impl.interceptor.CommandContext.performOperation(CommandContext.java:97)
	at org.activiti.engine.impl.jobexecutor.AsyncContinuationJobHandler.execute(AsyncContinuationJobHandler.java:35)
	at org.activiti.engine.impl.persistence.entity.JobEntity.execute(JobEntity.java:85)
	at org.activiti.engine.impl.persistence.entity.MessageEntity.execute(MessageEntity.java:34)
	at org.activiti.engine.impl.cmd.ExecuteJobsCmd.execute(ExecuteJobsCmd.java:88)
	at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:24)
	at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:57)
	at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:31)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:40)
	at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:35)
	at org.activiti.engine.impl.jobexecutor.ExecuteJobsRunnable.handleMultipleJobs(ExecuteJobsRunnable.java:94)
	at org.activiti.engine.impl.jobexecutor.ExecuteJobsRunnable.run(ExecuteJobsRunnable.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:808)
Caused by: org.cloudfoundry.client.lib.CloudFoundryException: 400 Could not create service "shine-container"
	at com.sap.cloud.lm.sl.cf.core.cf.clients.ServiceCreator.createService(ServiceCreator.java:44)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.createService(CreateOrUpdateServicesStep.java:335)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.lambda$createOrUpdateService$10(CreateOrUpdateServicesStep.java:241)
	at com.sap.cloud.lm.sl.cf.process.util.ServiceOperationExecutor.lambda$executeServiceOperation$0(ServiceOperationExecutor.java:14)
	at com.sap.cloud.lm.sl.cf.process.util.ServiceOperationExecutor.executeServiceOperation(ServiceOperationExecutor.java:21)
	at com.sap.cloud.lm.sl.cf.process.util.ServiceOperationExecutor.executeServiceOperation(ServiceOperationExecutor.java:13)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.createOrUpdateService(CreateOrUpdateServicesStep.java:241)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.createOrUpdateServices(CreateOrUpdateServicesStep.java:125)
	at com.sap.cloud.lm.sl.cf.process.steps.CreateOrUpdateServicesStep.pollStatusInternal(CreateOrUpdateServicesStep.java:94)
	... 40 more

**Comment by jeejo-j** [comment]
there was a setup issue with hana service and service plan, now it is resolved.
