### ISSUE TITLE
Error starting application "shine-site-web": Some instances have crashed.

### ISSUE THREAD

**Issue by batkanov** [SAP/hana-shine-xsa#56]
Hello!
I'm trying to deploy shine.mtar application with Python runtime. I have built it from branch https://github.com/SAP/hana-shine-xsa/tree/HANA2.0-SPS03-python

During deploy I've faced with the following error:

```
Application "shine-web" started and available at "https://hxehost:51090"
 Creating application "shine-site-web" from MTA module "shine-site-web"...
 Uploading application "shine-site-web"...
 Staging application "shine-site-web"...
 Application "shine-site-web" staged
 Starting application "shine-site-web"...
 Error starting application "shine-site-web": Some instances have crashed. Check the logs of your application for more information.
 Unexpected error: A step of the process has failed. Retrying it may solve the issue.
ERR    Error starting application "shine-site-web": Some instances have crashed. Check the logs of your application for more information.
```

```
Connected, tailing logs for app "shine-site-web"...
5/11/19 11:32:55.972 AM [API] OUT   Cleared instance [state CRASHED, index 1] of droplet [id 1] of app 'shine-site-web' [Org 'HANAExpress', Space 'SAP'] at [hxehost:40345, pid 25762].
5/11/19 11:32:55.979 AM [API] ERR   Number of running instances for app 'shine-site-web' [Org 'HANAExpress', Space 'SAP'] is 0 but should be 1. Trying to adapt number of running instances...
5/11/19 11:32:56.180 AM [API] OUT   Starting instance [state STARTING, index 1] of droplet [id 1] of app 'shine-site-web' [Org 'HANAExpress', Space 'SAP'] at [hxehost:40349].
5/11/19 11:33:00.675 AM [APP/1-1] OUT   
5/11/19 11:33:00.676 AM [APP/1-1] OUT   ========================================
5/11/19 11:33:00.676 AM [APP/1-1] OUT                  Creating Flp Approuter
5/11/19 11:33:00.676 AM [APP/1-1] OUT   ========================================
5/11/19 11:33:00.676 AM [APP/1-1] OUT   
5/11/19 11:33:00.686 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:682#+00:00#INFO#/server.js################PLAIN##
                                        ========================================
                                                       Registering user & cache middleware
                                        ========================================
                                        #
5/11/19 11:33:00.687 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:687#+00:00#INFO#/server.js################PLAIN##
                                        ========================================
                                                       Registering application middleware (for persistency service)
                                        ========================================
                                        #
5/11/19 11:33:00.688 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:687#+00:00#INFO#/toggles.js################PLAIN##Send request for toggles to: https://hxehost:51020/v1/toggles#
5/11/19 11:33:00.741 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:740#+00:00#INFO#/server.js################PLAIN##Toggles: {"SUPPORT_INDEPENDENT_APP":"true"}#
5/11/19 11:33:00.755 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:755#+00:00#INFO#/server.js################PLAIN##
                                        ========================================
                                                       Strating server ...
                                        ========================================
                                        #
5/11/19 11:33:00.756 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:756#+00:00#INFO#/server.js################PLAIN##Support independent app toggle: true#
5/11/19 11:33:00.782 AM [APP/1-1] SYS   #2.0#2019 05 11 11:33:00:779#+00:00#INFO#/approuter################PLAIN##Application router version 2.9.1#
5/11/19 11:33:00.797 AM [APP/1-1] ERR   
5/11/19 11:33:00.799 AM [APP/1-1] ERR   /hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/utils/JsonValidator.js:30
5/11/19 11:33:00.799 AM [APP/1-1] ERR       throw new VError('%s%s: %s',
5/11/19 11:33:00.799 AM [APP/1-1] ERR       ^
5/11/19 11:33:00.799 AM [APP/1-1] ERR   VError: xs-app.json/routes/9: Format validation failed (Route references unknown destination "user-java-backend")
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at JsonValidator.validate (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/utils/JsonValidator.js:30:11)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Object.validateXsApp (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/configuration/validators.js:74:15)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Object.exports.loadConfiguration (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/configuration/app-config.js:19:14)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Object.module.exports.load (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/configuration.js:19:34)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at bootstrap (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/lib/bootstrap.js:46:36)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Approuter.start (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/approuter/approuter.js:58:13)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at toggles.getToggles.toggles (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/site-entry/server.js:89:16)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Request.request.(anonymous function).err [as _callback] (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/@sap/site-entry/services/toggles.js:46:17)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at Request.self.callback (/hana/shared/HXE/xs/controller_data/executionagent/executionroot/f8733501-2302-4e69-8fef-a5c873a5035d/app/node_modules/request/request.js:187:22)
5/11/19 11:33:00.799 AM [APP/1-1] ERR       at emitTwo (events.js:106:13)
5/11/19 11:33:25.944 AM [API] OUT   Cleared instance [state CRASHED, index 2] of droplet [id 1] of app 'shine-site-web' [Org 'HANAExpress', Space 'SAP'] at [hxehost:40346, pid 25859].
```

Could you please help to resolve this issue?

**Comment by bbiswal333** [comment]
Issue is fixed.

**Comment by priyaptm154** [comment]
Hi , Can you let us know how u resolved tis issue

**Comment by venkateshannavarapu** [comment]
> Issue is fixed.

Hi ,
I am also facing same issue while deploying XS Module,Please help with resolution steps.

Regards,
Venkatesh Annavarapu,
+91-9441937817.
